### ISSUE TITLE
Pandoc syntax highlighting

### ISSUE THREAD

**Issue by kylebarron** [mcaceresb/highlight-sas-stata#1]
As of Pandoc 2.0 I think, Pandoc uses the [Skylighting](https://github.com/jgm/skylighting) library. Currently this doesn't color SAS or Stata code. This library is used for PDF, HTML, and docx output, so it would be useful to have syntax highlighting. I think there are currently some filters around that you can use to use Pygments instead, but only for PDF output of course.

Have you seen a Stata syntax file that uses the KDE XML syntax? If not I'll probably start my own from scratch, but won't spend a crazy amount of time on it.

**Comment by mcaceresb** [comment]
Kate highlights Stata (it has errors, but it recognizes the file and keywords). The current XML file is [here](https://kate-editor.org/syntax/5.28/stata.xml) I think. It looks like all it needs are better regexes (which I think my own files also need, so maybe this is a good time to update).

**Comment by kylebarron** [comment]
Thanks! I'll try to look into it in the next week or so. I use Pandoc a lot.
