### ISSUE TITLE
Operators highlighted in pygments?

### ISSUE THREAD

**Issue by kylebarron** [mcaceresb/highlight-sas-stata#3]
I haven't checked the output of pygments, but it appears that the `operators` key isn't called from anywhere... These are the only two occurrences of `operators`

https://github.com/mcaceresb/highlight-sas-stata/blob/22e29c354a3d73015142e75774c24d37566d432c/pygments/pygments/lexers/stata.py#L90-L94

**Comment by kylebarron** [comment]
Same with the `format` key

**Comment by mcaceresb** [comment]
Youthful omission? Rash decision? Either way I could just add

```
            include('keywords'),
            include('operators'),
```

to the `root` entry.

**Comment by mcaceresb** [comment]
I vaguely recall trying to decide whether to highlight both. I think I should have decided to highlight formatting but not operators, the former being possibly useful and the latter less so. However, I excluded both for some reason.

**Comment by kylebarron** [comment]
I wasn't sure if it was intentional or not

**Comment by mcaceresb** [comment]
94% sure it was, but I think I should have highlighted formats, even if I decided not to highlight operators.

**Comment by kylebarron** [comment]
I don't see why you wouldn't highlight either

**Comment by mcaceresb** [comment]
Indeed; you have moved me. The particulars of the highlighting should be handled by the style; the language definition should certainly include these things. Mistake on my end.

**Comment by kylebarron** [comment]
It's fine. Sometime I'll submit a pr to your repo maybe with comment highlighting updates. Then you or I can submit the modifications to the main pygments repo
