### ISSUE TITLE
missing highlight for ending parentheses

### ISSUE THREAD

**Issue by kylebarron** [mcaceresb/highlight-sas-stata#4]
It appears that HighlightJS is finally maintained again, or at least has someone active who is interested in merging things!!!

One bug I've noticed, closing parentheses don't get highlighted:
![image](https://user-images.githubusercontent.com/15164633/45332607-a4f6b980-b53f-11e8-9eb0-86c8d621a8eb.png)

This is present in both the HTML and PDF exports from Jupyter Notebook. I _think_ that means it's a Pygments problem, but I'm not sure.

**Comment by kylebarron** [comment]
https://github.com/mcaceresb/highlight-sas-stata/blob/22e29c354a3d73015142e75774c24d37566d432c/pygments/pygments/lexers/stata.py#L84-L86

that's why

**Comment by mcaceresb** [comment]
Really? Have you tried qtconsole?

PS: I didn't do the HLJS for Dtata.

**Comment by kylebarron** [comment]
![image](https://user-images.githubusercontent.com/15164633/45361825-2c284980-b5a1-11e8-885d-4c02420118f0.png)

**Comment by kylebarron** [comment]
I probably won't deal with highlight.js at all, since jupyter doesn't use it.
