### ISSUE TITLE
Pygments now being updated

### ISSUE THREAD

**Issue by kylebarron** [mcaceresb/highlight-sas-stata#8]
As I mentioned previously, Pygments hadn't had a release/any development since January 2017. They recently released an [updated version](https://pypi.org/project/Pygments/#history), so it might be of interested to make a PR to update the repo's Stata/Mata files.

**Comment by mcaceresb** [comment]
Cool. Yes, I should def get on this and integrate some of the more recent fixes. Hand-patching is no way to live. Will find time for it this week.

**Comment by kylebarron** [comment]
Any important updates to try to fix before creating the PR?

**Comment by mcaceresb** [comment]
It's on mercurial, right? I have to update my fork and push.

I was thinking of incorporating some of the Stata kernel lexer stuff (mata and #delimit).

**Comment by kylebarron** [comment]
Yes I believe so.

I'm not sure how much of that is useful for highlighting. The `#delimit ;` specifically is more useful for parsing code than highlighting it.

**Comment by mcaceresb** [comment]
The `#delimit` stuff would be for properly highlighting strings and comments. Might be too much work for the hassle. I'll mull it over. I'm updating my fork. Will circle when I'm done with that.

**Comment by mcaceresb** [comment]
This is up [here](https://bitbucket.org/mcaceresb/pygments-main/src/sas-stata/)

Do you think time is a concern? (i.e. should I make the PR right away and leave mata/delimit for later?)

**Comment by kylebarron** [comment]
I don't think it's urgent, since I try to add the new Pygments highlighting when starting the kernel anyways.

**Comment by mcaceresb** [comment]
k. I'll try and work on the mata and delimit stuff later today; hopefully it's not to too big of a hassle and I can make the PR soonish anyway.

**Comment by kylebarron** [comment]
Just pinging to make a PR to pygments

**Comment by mcaceresb** [comment]
I keep snoozing this on my TODO list. [Here](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/800); I just made it with the bug fixes. I'll add mata someday...

**Comment by mcaceresb** [comment]
Just got approved, yay!

**Comment by kylebarron** [comment]
Apparently there are merge conflicts

**Comment by mcaceresb** [comment]
I thought I solved them?

**Comment by kylebarron** [comment]
I just saw the comment from an hour ago

**Comment by mcaceresb** [comment]
I just pulled the default branch, merged, then pushed a few mins ago. Then it got approved.

I think I messed it up the first time bc I'm too used to git/github for this, which makes merging and pull-requests much easier.

**Comment by kylebarron** [comment]
You might want to ping the maintainer again
